image:
  file: Dockerfile.gitpod

ports:
  - name: Rails server
    port: 3000
    onOpen: open-preview
  - name: Demo application
    port: 4200
    onOpen: open-preview
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

tasks:
  - name: Setup
    init: |
      yarn install && yarn playwright install --with-deps
      # bundle install --gem-file examples/people2/Gemfile
      gp sync-done setup
    openMode: split-left
  - name: Start
    init: gp sync-await setup
    command: |
      yarn start
      # rake db:create
      # rails server -b 0.0.0.0
    openMode: split-right

vscode:
  extensions:
    - rebornix.ruby

jetbrains:
  rubymine:
    prebuilds:
      version: both
