image:
  file: Dockerfile.gitpod

ports:
  - name: Storybok / Docs
    port: 3000
    onOpen: open-preview
  - name: Frontend application
    port: 4200
    onOpen: open-preview
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

tasks:
  - name: Setup
    init: |
      # gem install rails rubocop solargraph htmlbeautifier
      yarn install
      yarn e2e:setup
      # pg_start
      gp sync-done setup
    openMode: split-left
  - name: Start
    init: gp sync-await setup
    command: yarn start
    openMode: split-right
