#!/usr/bin/env bash

set -eu
set -o pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly BIN_DIR="$(cd "${HOME}/bin" && pwd)"

# shellcheck source=SCRIPTDIR/util.sh
source "${SCRIPT_DIR}/util.sh"

if [[ $BASH_VERSINFO -lt 4 ]]; then
  print::error "Before running this script please update Bash to v4 or higher (e.g.: \$ sudo apt install bash)"
fi

function main() {
  local flags
  local os arch

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
    --help | -h)
      shift 1
      usage
      exit 0
      ;;

    "")
      # skip if the argument is empty
      shift 1
      ;;

    *)
      print::error "unknown argument \"${1}\""
      ;;
    esac
  done

  os=$(tools::os)
  arch=$(tools::arch)

  print::title "~~~> Running setup for os=${os} arch=${arch}\n--------------------------------------"

  print::title "\n~~~> Installing global ruby gems"
  gem install rails rubocop solargraph htmlbeautifier

  # TODO: Add an optional --skip-pg-start flag to skip this step
  print::title "\n~~~> Starting local postgres service"
  pg_start

  # print::title "\n~~~> Installing bit into ${BIN_DIR}"
  # tools::bit::install --directory "${BIN_DIR}"

  print::success "--------------------------------------\n~~~> Setup complete."
}

function usage() {
  cat <<-USAGE
scripts/setup [OPTIONS]

Install tools and frameworks into the local development environment.

OPTIONS
  --help       -h   prints the command usage
USAGE
}

main "${@:-}"
